/**
 * Backfill script: Populate chargeTo and origin for existing obligations
 * 
 * Logic:
 * - chargeTo is derived from type + paidBy + ownerImpact/agencyImpact
 * - origin is derived from isAutoGenerated and type
 * 
 * Run with: npx ts-node scripts/backfill-chargeto-origin.ts
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function backfill() {
  console.log('Starting backfill of chargeTo and origin...')

  const obligations = await prisma.obligation.findMany({
    select: {
      id: true,
      type: true,
      paidBy: true,
      ownerImpact: true,
      agencyImpact: true,
      isAutoGenerated: true,
      chargeTo: true,
      origin: true,
    }
  })

  console.log(`Found ${obligations.length} obligations to process`)

  let updated = 0
  let skipped = 0

  for (const ob of obligations) {
    // Skip if already has non-default values
    if (ob.origin !== null) {
      skipped++
      continue
    }

    // Derive chargeTo
    let chargeTo = 'tenant'
    switch (ob.type) {
      case 'rent':
        chargeTo = 'tenant'
        break
      case 'expenses':
        chargeTo = 'tenant'
        break
      case 'tax':
        chargeTo = 'owner'
        break
      case 'service':
      case 'insurance':
      case 'maintenance':
      case 'debt':
        if (ob.ownerImpact !== 0) {
          chargeTo = 'owner'
        } else if (ob.agencyImpact !== 0) {
          chargeTo = 'agency'
        } else {
          chargeTo = ob.paidBy || 'tenant'
        }
        break
      default:
        chargeTo = ob.paidBy || 'tenant'
    }

    // Derive origin
    let origin: string
    if (ob.isAutoGenerated) {
      origin = 'contract_auto'
    } else {
      // Manual obligations created before this migration
      // Default to tenant_ledger since that was the only creation point
      origin = 'tenant_ledger'
    }

    await prisma.obligation.update({
      where: { id: ob.id },
      data: { chargeTo, origin }
    })

    updated++
  }

  console.log(`Backfill complete: ${updated} updated, ${skipped} skipped`)
}

backfill()
  .catch((e) => {
    console.error('Backfill failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
